openapi: 3.0.1
info:
  title: Super Smash Bros. Ultimate REST Api
  description: 'Super Smash Bros. Ultimate RESTful Api'
  contact:
    email: projects.eclipse@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

paths:
  /character/{name}:
    get:
      tags:
        - Smash Ultimate Character
      summary: Returns Smash Bros. Ultiamte character data by name
      description: returns single character
      operationId: getCharacterByName
      parameters:
        - name: name
          in: path
          description: name of the character to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Character not found
          content: {}

  /character:
    post:
      tags:
        - Smash Ultimate Character
      summary: Creates Smash Bros. Ultiamte character data by name
      description: creates single character
      operationId: createCharacter
      responses:
        201:
          description: created character
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'

components:
  schemas:
    Character:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        groundedAttacks:
          $ref: '#/components/schemas/GroundedAttacks'
        aerialAttacks:
          $ref: '#/components/schemas/AerialAttacks'
        specialAttacks:
          $ref: '#/components/schemas/SpecialAttacks'
        grabsAndThrows:
          $ref: '#/components/schemas/GrabsAndThrows'
        dodgesAndRolls:
          $ref: '#/components/schemas/DodgesAndRolls'
        miscInfo:
          $ref: '#/components/schemas/MiscInfo'
    GroundedAttacks:
      type: array
      items:
        properties:
          name:
            type: string
          startup:
            type: string
          onShield:
            type: string
          active:
            type: string
          total:
            type: string
          note:
            type: string
          landingLag:
            type: string
          baseDmg:
            type: string
          shieldLag:
            type: string
          shieldStun:
            type: string
          additionalInfo:
            type: string
    AerialAttacks:
      type: array
      items:
        properties:
          name:
            type: string
          startup:
            type: string
          onShield:
            type: string
          active:
            type: string
          total:
            type: string
          note:
            type: string
          landingLag:
            type: string
          baseDmg:
            type: string
          shieldLag:
            type: string
          shieldStun:
            type: string
          additionalInfo:
            type: string

    SpecialAttacks:
      type: array
      items:
        properties:
          name:
            type: string
          startup:
            type: string
          onShield:
            type: string
          active:
            type: string
          total:
            type: string
          note:
            type: string
          landingLag:
            type: string
          baseDmg:
            type: string
          shieldLag:
            type: string
          shieldStun:
            type: string
          additionalInfo:
            type: string
    GrabsAndThrows:
      type: array
      items:
        properties:
          name:
            type: string
          startup:
            type: string
          active:
            type: string
          total:
            type: string
          note:
            type: string
          landingLag:
            type: string
          baseDmg:
            type: string

    DodgesAndRolls:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          total:
            type: string
          note:
            type: string
          landingLag:
            type: string
    MiscInfo:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          weight:
            type: string
          gravity:
            type: string
          walkSpeed:
            type: string
          runSpeed:
            type: string
          initialDash:
            type: string
          airSpeed:
            type: string
          totalAirAcceleration:
            type: string
          shFhShffFhffFrames:
            type: string
          fallSpeedFastFallSpeed:
            type: string
          ooSDownBAir:
            type: string
          ooSNeutralAir:
            type: string
          ooSDownAirUpSmash:
            type: string
          shieldGrab:
            type: string
          shieldDrop:
            type: string
          jumpSquat:
            type: string


